#!/usr/bin/env node
/**
 * Elahe Panel - Interactive Setup Wizard
 * Developer: EHSANKiNG
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise(resolve => rl.question(q, resolve));

async function setup() {
  console.log('\n╔══════════════════════════════════════╗');
  console.log('║      Elahe Panel v0.0.5 Setup        ║');
  console.log('║      Developer: EHSANKiNG             ║');
  console.log('╚══════════════════════════════════════╝\n');

  const mode = await ask('Server mode? (iran/foreign) [iran]: ') || 'iran';
  const port = await ask('Server port? [3000]: ') || '3000';
  const adminUser = await ask('Admin username? [admin]: ') || 'admin';
  const adminPass = await ask('Admin password? [admin]: ') || 'admin';

  let irTitle = 'گذر تحریم';
  let irPrimary = '#1a73e8';
  let irSecondary = '#34a853';
  let irAccent = '#fbbc04';
  let enTitle = 'Linux Academy';
  let enPrimary = '#0f172a';
  let enSecondary = '#3b82f6';
  let enAccent = '#10b981';

  if (mode === 'iran') {
    console.log('\n--- Iran Site Configuration ---');
    console.log('Using default Iran camouflage theme.');
  } else {
    console.log('\n--- Foreign Site Configuration ---');
    console.log('Using default Linux Academy camouflage theme.');
  }

  const coreEngine = await ask('Core engine? (xray/singbox) [xray]: ') || 'xray';

  // Generate secrets
  const sessionSecret = crypto.randomBytes(32).toString('hex');
  const jwtSecret = crypto.randomBytes(64).toString('hex');

  // Create .env file
  const envContent = `# Elahe Panel Configuration
# Generated by setup wizard
ELAHE_MODE=${mode}
PORT=${port}
HOST=127.0.0.1
SESSION_SECRET=${sessionSecret}
JWT_SECRET=${jwtSecret}
ADMIN_USER=${adminUser}
ADMIN_PASS=${adminPass}
CORE_ENGINE=${coreEngine}

# Iran Site
IR_TITLE=${irTitle || ''}
IR_PRIMARY=${irPrimary || '#1a73e8'}
IR_SECONDARY=${irSecondary || '#34a853'}
IR_ACCENT=${irAccent || '#fbbc04'}

# Foreign Site
EN_TITLE=${enTitle || ''}
EN_PRIMARY=${enPrimary || '#0f172a'}
EN_SECONDARY=${enSecondary || '#3b82f6'}
EN_ACCENT=${enAccent || '#10b981'}

# Database
DB_PATH=./data/elahe.db

# Logging
LOG_LEVEL=info
`;

  const envPath = path.join(__dirname, '..', '.env');
  fs.writeFileSync(envPath, envContent);
  console.log(`\n✓ Configuration saved to .env`);

  // Initialize database
  console.log('✓ Initializing database...');
  const { migrate } = require('../src/database/migrate');
  migrate();
  console.log('✓ Database initialized');

  // Ensure admin credentials are updated
  const Database = require('better-sqlite3');
  const bcrypt = require('bcryptjs');
  const dbPath = path.join(__dirname, '..', 'data', 'elahe.db');
  const db = new Database(dbPath);
  const hash = bcrypt.hashSync(adminPass, 10);
  const existing = db.prepare('SELECT id FROM admins WHERE username = ?').get(adminUser);
  if (existing) {
    db.prepare('UPDATE admins SET password = ?, status = ?, is_sudo = 1 WHERE id = ?')
      .run(hash, 'active', existing.id);
  } else {
    db.prepare('INSERT INTO admins (username, password, is_sudo, status) VALUES (?, ?, 1, ?)')
      .run(adminUser, hash, 'active');
  }
  if (adminUser !== 'admin') {
    db.prepare('UPDATE admins SET status = ? WHERE username = ?').run('disabled', 'admin');
  }
  db.close();
  console.log('✓ Admin credentials updated');

  console.log('\n╔══════════════════════════════════════╗');
  console.log('║          Setup Complete!              ║');
  console.log('╠══════════════════════════════════════╣');
  console.log(`║  Mode:     ${mode.padEnd(26)}║`);
  console.log(`║  Port:     ${port.padEnd(26)}║`);
  console.log('║  Public:   443 (via Nginx)            ║');
  console.log(`║  Admin:    ${adminUser.padEnd(26)}║`);
  console.log(`║  Engine:   ${coreEngine.padEnd(26)}║`);
  console.log('╠══════════════════════════════════════╣');
  console.log('║  Start: npm start                    ║');
  console.log('║  Dev:   npm run dev                  ║');
  console.log('╚══════════════════════════════════════╝\n');

  rl.close();
}

setup().catch(err => { console.error('Setup failed:', err); rl.close(); process.exit(1); });
