#!/usr/bin/env node
/**
 * Elahe Panel - Interactive Setup Wizard
 * Developer: EHSANKiNG
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise(resolve => rl.question(q, resolve));

async function setup() {
  console.log('\n╔══════════════════════════════════════╗');
  console.log('║      Elahe Panel v0.0.3 Setup        ║');
  console.log('║      Developer: EHSANKiNG             ║');
  console.log('╚══════════════════════════════════════╝\n');

  const mode = await ask('Server mode? (iran/foreign) [iran]: ') || 'iran';
  const port = await ask('Server port? [3000]: ') || '3000';
  const adminUser = await ask('Admin username? [admin]: ') || 'admin';
  const adminPass = await ask('Admin password? [admin]: ') || 'admin';

  let irTitle, irPrimary, irSecondary, irAccent;
  let enTitle, enPrimary, enSecondary, enAccent;

  if (mode === 'iran') {
    console.log('\n--- Iran Site Configuration ---');
    irTitle = await ask('Site title (Persian)? [گذر تحریم]: ') || 'گذر تحریم';
    irPrimary = await ask('Primary color? [#1a73e8]: ') || '#1a73e8';
    irSecondary = await ask('Secondary color? [#34a853]: ') || '#34a853';
    irAccent = await ask('Accent color? [#fbbc04]: ') || '#fbbc04';
  } else {
    console.log('\n--- Foreign Site Configuration ---');
    enTitle = await ask('Site title? [CloudShield DNS]: ') || 'CloudShield DNS';
    enPrimary = await ask('Primary color? [#0f172a]: ') || '#0f172a';
    enSecondary = await ask('Secondary color? [#3b82f6]: ') || '#3b82f6';
    enAccent = await ask('Accent color? [#10b981]: ') || '#10b981';
  }

  const coreEngine = await ask('Core engine? (xray/singbox) [xray]: ') || 'xray';

  // Generate secrets
  const sessionSecret = crypto.randomBytes(32).toString('hex');
  const jwtSecret = crypto.randomBytes(64).toString('hex');

  // Create .env file
  const envContent = `# Elahe Panel Configuration
# Generated by setup wizard
ELAHE_MODE=${mode}
PORT=${port}
HOST=0.0.0.0
SESSION_SECRET=${sessionSecret}
JWT_SECRET=${jwtSecret}
ADMIN_USER=${adminUser}
ADMIN_PASS=${adminPass}
CORE_ENGINE=${coreEngine}

# Iran Site
IR_TITLE=${irTitle || ''}
IR_PRIMARY=${irPrimary || '#1a73e8'}
IR_SECONDARY=${irSecondary || '#34a853'}
IR_ACCENT=${irAccent || '#fbbc04'}

# Foreign Site
EN_TITLE=${enTitle || ''}
EN_PRIMARY=${enPrimary || '#0f172a'}
EN_SECONDARY=${enSecondary || '#3b82f6'}
EN_ACCENT=${enAccent || '#10b981'}

# Database
DB_PATH=./data/elahe.db

# Logging
LOG_LEVEL=info
`;

  const envPath = path.join(__dirname, '..', '.env');
  fs.writeFileSync(envPath, envContent);
  console.log(`\n✓ Configuration saved to .env`);

  // Initialize database
  console.log('✓ Initializing database...');
  const { migrate } = require('../src/database/migrate');
  migrate();
  console.log('✓ Database initialized');

  console.log('\n╔══════════════════════════════════════╗');
  console.log('║          Setup Complete!              ║');
  console.log('╠══════════════════════════════════════╣');
  console.log(`║  Mode:     ${mode.padEnd(26)}║`);
  console.log(`║  Port:     ${port.padEnd(26)}║`);
  console.log(`║  Admin:    ${adminUser.padEnd(26)}║`);
  console.log(`║  Engine:   ${coreEngine.padEnd(26)}║`);
  console.log('╠══════════════════════════════════════╣');
  console.log('║  Start: npm start                    ║');
  console.log('║  Dev:   npm run dev                  ║');
  console.log('╚══════════════════════════════════════╝\n');

  rl.close();
}

setup().catch(err => { console.error('Setup failed:', err); rl.close(); process.exit(1); });
